### PR TITLE
Fix #533

### LINKED ISSUE #533: type checking in `Signal.sampling_rate`
The `sampling_rate` kwarg in the `Signal` constructor is not thoroughly typechecked or parsed which leads to errors down the line that are hard to backtrace. IMO `sampling_rate` should be cast as an integer. Of course having `sampling_rate` as a 2d-array is not a great design choice but happens sometimes, e.g. when reading data from `.mat` files

 
MWE:
``` python
import numpy as np
import pyfar as pf

n = np.random.rand(100)
fs = np.array([[100]])
sig = pf.Signal(n, sampling_rate=fs)
pf.plot.group_delay(sig) # this fails
```

### LINKED ISSUE #553: Retaining the phase for FFT normalizations `'power'` and `'psd'` is obsolete
## General

* pyfar version: 0.6.4

## Description

[pyfar.dsp.normalization](https://pyfar.readthedocs.io/en/stable/_modules/pyfar/dsp/fft.html#normalization) retaines the phase information for the normalizations `'power'` and `'psd'`, though there are regularly defined as real-valued only.
I think this is a leftover from before the `signal.freq_raw` property was introduced in 0.4.0 (PR #274), which stores the spectrum without normalization (incl. phase). We should consider removing phase information to have coherent definitions.

## What I Did

```
import pyfar as pf
import numpy as np

signal = pf.signals.noise(44100)
signal.fft_norm = 'psd'
pf.plot.freq_phase(signal)
```
image

### PR DESCRIPTION
**Pull request by artpelling**
Closes #533

### CODE REVIEW

**Review by mberz — CHANGES_REQUESTED** [review]
Thanks for implementing.
I'm a bit unsure though about the implicit and arbitrary selection of a single value from an array here. I think I'd prefer if this is a bit more verbose, otherwise users might assume that multi-rate signals are supported. 
Could your maybe add a warning?
Also I was thinking if this could additionally check if the array is longer than a single entry and raise an exception in this case.

**Comment by f-brinkmann** [comment]
> Could your maybe add a warning? Also I was thinking if this could additionally check if the array is longer than a single entry and raise an exception in this case.

Maybe it's sufficient to raise an exception if there are more then one entry and convert silently otherwise?

**Comment by mberz** [comment]
I'd also be okay with that.

**Comment by pingelit** [comment]
Thanks for the effort, I agree with the suggestion by f-brinkmann to to raise an exception if there are more than one entry.

**Review by mberz — APPROVED** [review]

**Pull request merged**
