### PR TITLE
Switch to the PyData Sphinx theme

### PR DESCRIPTION
**Pull request by mberz**
I find this theme a bit easier to navigate and also easier on the eyes. But I guess it boils down to personal preference. Have a look at it yourselves.

https://pyfar--545.org.readthedocs.build/en/545/

### CODE REVIEW

**Comment by sikersten** [comment]
+1 for PyData Sphinx theme

**Review by pingelit — APPROVED** [review]
Thanks for the PR. This theme looks much better.

**Review by ahms5 — APPROVED** [review]

**Review by f-brinkmann — CHANGES_REQUESTED** [review]
Lets pick some code from the gallery after launching it in the next weekly

**Review by sikersten — APPROVED** [review]

**Comment by mberz** [comment]
I'll include and adapt to the gallery's configuration, once https://github.com/pyfar/gallery/pull/29 is finalised and ready to be merged.

**Comment by ahms5** [comment]
replaced by #560

**Pull request closed without merging**
