### PR TITLE
restructure pyfar doc

### PR DESCRIPTION
**Pull request by hoyer-a**
New pyfar documentation: https://pyfar--653.org.readthedocs.build/en/653/pyfar.html

Maybe add a little more explanation on the api-reference? E.g. in sofar we briefly explain the purpose of the classes.

### CODE REVIEW

**Review by ahms5 — CHANGES_REQUESTED** [review]
thank you, looks fine! 
not sure if we need more explaination, we already refer to the examples.
we can also add the logo for pyfar in the readme, as we did in sofar.

**Review by f-brinkmann — CHANGES_REQUESTED** [review]
I agree with @ahms5 that we don't need more information and could add the logo.

I would suggest to put the first sentence of the readme to the index page of the pyfar docs and change it to (also in the readme): 'The python package for acoustics research (pyfar) offers classes to store audio data, filters, coordinates, and orientations. It also contains functions reading and writing audio data, as well as functions for processing, generating, and plotting audio signals.'

**Review by f-brinkmann — APPROVED** [review]
Thanks - fine for me :)

**Review by ahms5 — APPROVED** [review]

**Review by sikersten — APPROVED** [review]
Thank you, very nice!

**Pull request merged**
