### PR TITLE
Replace scipy's legacy spectrogram with new implementaton

### LINKED ISSUE #667: `dsp.spectrogram` relies on scipy's `spectrogram` which is considered legacy
## General

* pyfar version: 0.6.8

## Description

`dsp.spectrogram()` relies on [scipy.signal.spectrogram](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.spectrogram.html) which is considered legacy. 

The use of [scipy.signal.ShortTimeFFT](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.ShortTimeFFT.html#scipy.signal.ShortTimeFFT) is recommended.

### PR DESCRIPTION
**Pull request by hoyer-a**
Replace [scipy.signal.spectrogram](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.spectrogram.html#scipy.signal.spectrogram) with [scipy.signal.ShortTimeFFT](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.ShortTimeFFT.html#scipy.signal.ShortTimeFFT) and new [spectrogram-method](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.ShortTimeFFT.spectrogram.html#scipy.signal.ShortTimeFFT.spectrogram).

Based on: https://docs.scipy.org/doc/scipy/tutorial/signal.html#short-time-fourier-transform

Closes #667

### CODE REVIEW

**Review by ahms5 — DISMISSED** [review]
if we decide to kick python 3.8 out, I think its time.
https://docs.scipy.org/doc/scipy-1.13.0/release/1.12.0-notes.html

**Review by f-brinkmann — CHANGES_REQUESTED** [review]
Can you please check if the Python 3.8 tests still work if you restrinct scipy in setup.py to the version where `ShortTimeFFT` was introduced? If not I would also be in favor of dropping Python 3.8 support.

**Comment by f-brinkmann** [comment]
@tluebeck, once this is merged, it will probably give a conflict with the develop signal branch

**Comment by ahms5** [comment]
> Can you please check if the Python 3.8 tests still work if you restrinct scipy in setup.py to the version where `ShortTimeFFT` was introduced? If not I would also be in favor of dropping Python 3.8 support.

maybe that wouldn't even work, (and if, we should leave it anyway) since they have stopped supporting 3.8 with the same version.

**Comment by f-brinkmann** [comment]
> maybe that wouldn't even work, (and if, we should leave it anyway) since they have stopped supporting 3.8 with the same version.

Ah, ok. In this case I would vote for dropping 3.8 but merging this into develop for release with 0.7.0. Might be a bit unexpected to deprecate a Python version in a patch release.

**Comment by sikersten** [comment]
+1 for dropping 3.8. with 0.7.0 release. I think this might also affect #636, @ph-schaefer

**Comment by f-brinkmann** [comment]
We decided to deprecate Python 3.8 in pyfar 0.7.0. This will be a separate pull.

**Review by ahms5 — APPROVED** [review]
requires #683

**Review by f-brinkmann — APPROVED** [review]

**Pull request merged**
