### PR TITLE
fix erroneous default mentioned in docstring

### LINKED ISSUE #558: Documentation of `fractional_octave_bands` has a minor error with default value for `num_fractions`
## General

* pyfar version: 0.6..4

## Description

The documentation of [`fractional_octave_bands`](https://pyfar.readthedocs.io/en/stable/modules/pyfar.dsp.filter.html#pyfar.dsp.filter.fractional_octave_bands) states, that the default of `num_fractions` is 1. But it has no default value.

### PR DESCRIPTION
**Pull request by f-brinkmann**
### Which issue(s) are closed by this pull request?

Closes #558

### CODE REVIEW

**Review by ahms5 — APPROVED** [review]
isnt it a hotifx?

**Comment by f-brinkmann** [comment]
We could consider it to be one

**Comment by f-brinkmann** [comment]
@f-brinkmann we decided to make it a hotfix - cherry pick and merge...

**Comment by f-brinkmann** [comment]
closed in favor or #650

**Pull request closed without merging**
