### PR TITLE
Improve developer documentation

### PR DESCRIPTION
**Pull request by f-brinkmann**
### Which issue(s) are closed by this pull request?

Improve developer documentation for adding read/write support to pyfar objects.

Note that the docstring references a function that is not merged into develop yet: https://github.com/pyfar/pyfar/blob/feature/auditory_filters/pyfar/dsp/filter/gammatone.py

### CODE REVIEW

**Review by sikersten — APPROVED** [review]
Looks good, thanks!

**Comment by Agent49** [comment]
Looks good! Thank you!

**Comment by Agent49** [comment]
Looks good! Thank you!

**Review by Agent49 — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
