### PR TITLE
Remove unwanted minor tick label for log plots

### LINKED ISSUE #71: Log formatter  for plots adds unwanted ticks in scientific notation
## Description

`pyfar.plot.ticker.Log*.py` add unwanted ticks depending on the axis range

## What I Did

```
import numpy as np
import pyfar.plot as pp

# this is fine
sin = np.sin(np.linspace(0, 2000*np.pi, 10000))
x = Signal(sin, 44100, fft_norm='amplitude')
ax = pp.line.freq(x)

# this generates an unwanted tick at 300 Hz
ax.set_xlim(50, 425)
```

### PR DESCRIPTION
**Pull request by pingelit**
### Which issue(s) are closed by this pull request?

Closes #71

### Changes proposed in this pull request:

- Disable the minor tick labels for log axis to remove the unwanted tick labels.

### CODE REVIEW

**Comment by pingelit** [comment]
So far I've only added this to the `freq` plot, due to some open questions:

- Is this what we want? #71 suggests another approach.
- Should this be the default, even for `freq_scale='linear'`

**Comment by f-brinkmann** [comment]
Thanks for checking, I think it resolves the issue. I did not see any effect on linear axes. Applying it only to log. frequency axis might be the cleaner solution as it would maintain as much Matplotlib default behavior as possible.

**Review by mberz — COMMENTED** [review]
Just minor things.
I'd also agree to not use this for linearly scaled axes.
We should not close #71 though, or create a new issue, since this only fixes part of the issue. The other problem is that one may end up with a very low number (or on extreme cases none) of major ticks when zooming in on the frequency axis.

**Comment by f-brinkmann** [comment]
Agreed and opened a new issue with a more specific name #451

**Comment by pingelit** [comment]
Just fixed the comments from @mberz.
Before opening the pull request, I want to check if this behavior can be unit tested.

**Review by f-brinkmann — APPROVED** [review]

**Review by f-brinkmann — APPROVED** [review]
Thanks for implementing!

**Pull request merged**
