### PR TITLE
Migrate to `hatch`-based `pyproject.toml` config

### PR DESCRIPTION
**Pull request by artpelling**
# TODO:
- [ ] `bump2version` is no longer maintained
- [ ] fix syntax in `CHANGELOG.md` if change is kept
- [ ] make doc build clean and check dependencies
- [ ] hatch-based testing
- [ ] go through packaging process
- [ ] situation with main devs? who is that, add maintainers section
- [ ] add better keywords
- [ ] pin `ruff` version?

### CODE REVIEW

**Comment by artpelling** [comment]
> Thanks for making this initial push. I assume it's a good basis to have a more extensive discussion during one of the meetings. One important question comes to my mind at this point: CircleCI has their own management for python versions, allowing for parallel execution etc. Can hatch integrate well with CircleCI's infrastructure?

I never worked with CircleCI so I don't know about how it works but at a quick glance I don't see any issue. We can go into some details in friday :)

**Comment by ahms5** [comment]
I have tried a bit in pr #700, my findings were:
- Sometimes it is difficult to find documentation for what you really need. Generally the documentation is not that good and does not really deal with edge cases.
- Sometimes it just stopped working. 2 minutes ago the hatch command was working, then it stopped working, I'm missing an option to restart it.
- ``hatch fmt'' uses build in ruff for check and for format, I have not yet discovered how to disable the format stuff.
- Building the documentation has not worked so far, no idea whats happening, Im running ``hatch run docs:build`` and getting ``Environment `docs` is incompatible: unsupported platform.
- I have not managed to add more input to pytest, e.g. to test for deprecations.
- The community is not very big now, so you will not find much on the web apart from the docs.

If you want to have a look or try it out, feel free to use PR #700.

**Comment by pingelit** [comment]
I think most of your points are easily solvable. Once I have a bit more time to spare, I can check it out.

**Comment by mberz** [comment]
closing in favor of #710

**Pull request closed without merging**
